### ISSUE TITLE
Imports for Nodejs headless mode not working anymore on v0.25.0

### ISSUE THREAD

**Issue by finkton1** [enable3d/enable3d-website#54]
When trying to use new version of

Error: Cannot find module '[DIRECTORY]\@enable3d\ammo-on-nodejs\dist\index.js'. Please verify that the package.json has a valid "main" entry.

The culprit is:

`const { Physics, ServerClock } = require('@enable3d/ammo-on-nodejs');`

This works on v 0.24.0 however... I noticed in package.json for the lib references entrypoint of "/dist" - this no longer exists in v0.25.0
